### ISSUE TITLE
Integrity

### ISSUE THREAD

**Issue by IzzySoft** [robinvanemden/BabyApp#1]
Just wanted to let you know that [there's a VirusTotal report on your latest release](https://www.virustotal.com/de/file/a084810a1d37adfba95f593e4d443d55972ebe41e3823c36138666505e830e16/analysis/1481226137/), showing that 1 out of 58 engines blames it to include "Android.Malware.CertV1". I've requested a couple of rescans during the past few days to rule out a "bad signature" that might have been fixed, but it sticks. The very same engine also claims the very same thing [for other apps](https://virustotal.com/sk/file/fd5e4275a2443d823b09e184bc9efc56b60b48eae37fa5f77b02d05dd2373665/analysis/1479582552/), but always stays alone with its claim – so I rather suspect a "false positive" here. Nevertheless, I thought you should know. Not blaming anything (except maybe that scanner :stuck_out_tongue_winking_eye:).

**Comment by robinvanemden** [comment]
Hi IzzySoft,
Thanks for bringing this to my attention! Can really be nothing but a false positive, as the code is quite straightforward and makes use of just three oft implemented open source libraries. Still, I will look into it this nevertheless. An update of the libraries and a rebuild may already fix this false positive somehow, who knows :relaxed:

**Comment by robinvanemden** [comment]
Still no clue as to why the APK was not rated safe. Yet a recompile and some permission cleaning seems to have done the trick - the app is now judged to be safe by all scanners [rated safe](https://www.virustotal.com/de/file/3c3f50f556546a88fa6cd2e1591b32ffe9b603d2d9b00b3f8d21d296d29f47a6/analysis/). Anyway, thanks again for the heads-up!

**Comment by IzzySoft** [comment]
Thanks for the fast fix, @robinvanemden ! May I suggest (for the future) that you also increase `versionCode` and `versionName` for new APKs? I just received a "duplicate versions" error from my fdroidserver (find your app [listed here](https://apt.izzysoft.de/fdroid/index/apk/com.hollandhaptics.babyapp) :smile_cat: )

    package: name='com.hollandhaptics.babyapp' versionCode='1' versionName='1.0' platformBuildVersionName='7.1.1'
