### ISSUE TITLE
Scheduled

### ISSUE THREAD

**Issue by kostar** [robinvanemden/BabyApp#2]
Hi! Is there any way to schedule the recorder only during certain hours and days with repeat option? For example, record sound only between 11 PM and 6 AM.

**Comment by robinvanemden** [comment]
Hi Kostar,
Not as of yet - though it would not be very difficult to add this particular feature. 

One idea might be to just keep the service running in the background, and only start recording when between 11pm and 6am. For example by making use of [this function](https://stackoverflow.com/questions/17697908/check-if-a-given-time-lies-between-two-times-regardless-of-date/28208889#28208889) to check whether it's between 11 PM and 6 AM.

Of course, starting and stopping the background service at the specified times might be better - some examples of how to go about that can be found [here](https://www.sitepoint.com/scheduling-background-tasks-android/) and [here](https://stackoverflow.com/questions/26885731/how-to-start-service-and-stop-service-based-on-time-interval-in-android).

**Comment by kostar** [comment]
easy for you to say :)
